name: ft_transcendence_dev

services:

  postgresql:
    build:
      context: ./postgres
      dockerfile: dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./front/tools:/usr/src/app/
      - front_node_modules:/usr/src/app/node_modules
    depends_on:
      - user-service
    restart: always

  gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway/tools:/usr/src/app/
      - gateway_node_modules:/usr/src/app/node_modules
    depends_on:
      - user-service
      - postgresql
    restart: always

  user-service:
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    container_name: user-service-container
    env_file:
      - ./user-service/.env
    ports:
      - "4000:4000"
    volumes:
      - ./user-service/tools:/usr/src/app/
      - user-service_node_modules:/usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma/
    depends_on:
      - postgresql
    restart: always

  chat-service:
    build:
      context: ./chat-service/
      dockerfile: Dockerfile
    container_name: chat-service-container
    env_file:
      - ./chat-service/.env.local
    ports:
      - "4002:4002"
    volumes:
      - ./chat-service/tools:/usr/src/app/
      - chat-service_node_modules:/usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma/
    depends_on:
      - postgresql
    restart: always

  game-service:
    build:
      context: ./game-service/
      dockerfile: Dockerfile
    container_name: game-service-container
    env_file:
      - ./game-service/.env.local
    ports:
      - "9090:9090"  # WebSocket port
      - "4003:4003"  # HTTP API port
    depends_on:
      - postgresql
    volumes:
      - ./game-service/tools:/usr/src/app/
      - game-service_node_modules:/usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma/
    restart: always

  log-service:
    build:
      context: ./log-service/
      dockerfile: Dockerfile
    container_name: log-service-container
    env_file:
      - ./log-service/.env
    ports:
      - "4001:4001"
    volumes:
      - ./log-service/tools:/usr/src/app/
      - log-service_node_modules:/usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma/
    depends_on:
      - postgresql
    restart: always

volumes:
  postgres_data:
  front_node_modules:
  gateway_node_modules:
  user-service_node_modules:
  chat-service_node_modules:
  game-service_node_modules:
  log-service_node_modules: